#define WINDOW_HEIGHT 980
#define WINDOW_WIDTH 1680
#define WINDOW_TITLE "Star Wars"
#define PLAYER_HEIGHT 180
#define PLAYER_WIDTH 100
#define PLAYER_SPEED 1
#define RUNNIG_DELAY 1
#define PLAYER_BULLET_SPEED 2
#define PLAYER_BULLET_HEIGHT 30
#define PLAYER_BULLET_WIDTH 10
#define ENEMY_BULLET_SPEED 1
#define ENEMY_BULLET_HEIGHT 30
#define ENEMY_BULLET_WIDTH 10
#define ENEMY_WIDTH 70
#define ENEMY_HEIGHT 100